/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */

synchronized public void win_draw3(PApplet appc, GWinData data) { //_CODE_:window2:730751:
  appc.background(230);
} //_CODE_:window2:730751:

public void sss(GCustomSlider source, GEvent event) { //_CODE_:Speed:287057:
  println("custom_slider1 - GCustomSlider >> GEvent." + event + " @ " + millis());
  frameRate(Speed.getValueF());
} //_CODE_:Speed:287057:

public void button1_click1(GButton source, GEvent event) { //_CODE_:Explode:603350:
  println("Explode - GButton >> GEvent." + event + " @ " + millis());
  explodeAll();
} //_CODE_:Explode:603350:



// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.BLUE_SCHEME);
  G4P.setMouseOverEnabled(false);
  surface.setTitle("Sketch Window");
  window2 = GWindow.getWindow(this, "Window title", 0, 0, 240, 120, JAVA2D);
  window2.noLoop();
  window2.setActionOnClose(G4P.KEEP_OPEN);
  window2.addDrawHandler(this, "win_draw3");
  Speed = new GCustomSlider(window2, 70, 40, 100, 40, "grey_blue");
  Speed.setLimits(0.5, 0.0, 30.0);
  Speed.setNumberFormat(G4P.DECIMAL, 2);
  Speed.setOpaque(false);
  Speed.addEventHandler(this, "sss");
  Explode = new GButton(window2, 81, 80, 80, 30);
  Explode.setText("Explode");
  Explode.addEventHandler(this, "button1_click1");
  window2.loop();
}

// Variable declarations 
// autogenerated do not edit
GWindow window2;
GCustomSlider Speed; 
GButton Explode; 
