/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */

synchronized public void controlsWindow_draw1(PApplet appc, GWinData data) { //_CODE_:controlsWindow:918147:
  appc.background(230);
} //_CODE_:controlsWindow:918147:

public void bSliderChanged(GSlider source, GEvent event) { //_CODE_:bSlider:563356:
  resetParameters();
} //_CODE_:bSlider:563356:

public void speedSliderChanged(GSlider source, GEvent event) { //_CODE_:speedSlider:843400:
  resetParameters();
} //_CODE_:speedSlider:843400:

public void numRaysTextfieldChanged(GTextField source, GEvent event) { //_CODE_:numRaysTextfield:778730:
  resetParameters();
} //_CODE_:numRaysTextfield:778730:

public void bulbPlacementListChanged(GDropList source, GEvent event) { //_CODE_:bulbPlacementList:878161:
  resetParameters();
} //_CODE_:bulbPlacementList:878161:

public void aSliderChanged(GSlider source, GEvent event) { //_CODE_:aSlider:251711:
  resetParameters();
} //_CODE_:aSlider:251711:

public void rayParticlesButtonClicked(GButton source, GEvent event) { //_CODE_:rayParticlesButton:598733:
  if(drawingMode.equals("particles")) {
    drawingMode = "rays";
    rayParticlesButton.setText("Draw particles");
  }
    
  else {
    drawingMode = "particles";
    rayParticlesButton.setText("Draw rays");
  }
} //_CODE_:rayParticlesButton:598733:



// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.BLUE_SCHEME);
  G4P.setCursor(ARROW);
  surface.setTitle("Sketch Window");
  controlsWindow = GWindow.getWindow(this, "controls", 0, 0, 500, 400, JAVA2D);
  controlsWindow.noLoop();
  controlsWindow.addDrawHandler(this, "controlsWindow_draw1");
  label1 = new GLabel(controlsWindow, 10, 30, 100, 20);
  label1.setText("Ellipse height");
  label1.setTextBold();
  label1.setOpaque(false);
  bSlider = new GSlider(controlsWindow, 120, 20, 229, 40, 10.0);
  bSlider.setShowValue(true);
  bSlider.setLimits(75, 10, 100);
  bSlider.setNbrTicks(10);
  bSlider.setNumberFormat(G4P.INTEGER, 0);
  bSlider.setOpaque(false);
  bSlider.addEventHandler(this, "bSliderChanged");
  label2 = new GLabel(controlsWindow, 10, 120, 80, 20);
  label2.setText("Ray speed");
  label2.setOpaque(false);
  speedSlider = new GSlider(controlsWindow, 90, 110, 172, 40, 10.0);
  speedSlider.setShowValue(true);
  speedSlider.setLimits(2, 0, 10);
  speedSlider.setNbrTicks(10);
  speedSlider.setNumberFormat(G4P.INTEGER, 0);
  speedSlider.setOpaque(false);
  speedSlider.addEventHandler(this, "speedSliderChanged");
  label3 = new GLabel(controlsWindow, 10, 180, 158, 20);
  label3.setText("Number of rays (max 600)");
  label3.setOpaque(false);
  numRaysTextfield = new GTextField(controlsWindow, 170, 180, 50, 30, G4P.SCROLLBARS_NONE);
  numRaysTextfield.setText("1000");
  numRaysTextfield.setOpaque(true);
  numRaysTextfield.addEventHandler(this, "numRaysTextfieldChanged");
  label4 = new GLabel(controlsWindow, 10, 230, 129, 20);
  label4.setText("Light bulb placement");
  label4.setOpaque(false);
  bulbPlacementList = new GDropList(controlsWindow, 150, 230, 150, 220, 10);
  bulbPlacementList.setItems(loadStrings("list_878161"), 0);
  bulbPlacementList.addEventHandler(this, "bulbPlacementListChanged");
  label6 = new GLabel(controlsWindow, 10, 70, 100, 20);
  label6.setText("Ellipse width");
  label6.setOpaque(false);
  aSlider = new GSlider(controlsWindow, 120, 60, 230, 40, 10.0);
  aSlider.setShowValue(true);
  aSlider.setLimits(75, 10, 100);
  aSlider.setNumberFormat(G4P.INTEGER, 0);
  aSlider.setOpaque(false);
  aSlider.addEventHandler(this, "aSliderChanged");
  rayParticlesButton = new GButton(controlsWindow, 10, 270, 80, 30);
  rayParticlesButton.setText("Draw particles");
  rayParticlesButton.addEventHandler(this, "rayParticlesButtonClicked");
  controlsWindow.loop();
}

// Variable declarations 
// autogenerated do not edit
GWindow controlsWindow;
GLabel label1; 
GSlider bSlider; 
GLabel label2; 
GSlider speedSlider; 
GLabel label3; 
GTextField numRaysTextfield; 
GLabel label4; 
GDropList bulbPlacementList; 
GLabel label6; 
GSlider aSlider; 
GButton rayParticlesButton; 
