/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */

synchronized public void win_draw1(PApplet appc, GWinData data) { //_CODE_:controlsWindow:309407:
  appc.background(230);
} //_CODE_:controlsWindow:309407:

public void pauseButtonClicked(GButton source, GEvent event) { //_CODE_:pauseButton:882984:
  paused = !paused;
  
  if( paused  )
    pauseButton.setText("Go");
    
  else
    pauseButton.setText("Pause");
    
} //_CODE_:pauseButton:882984:


public void gridSizeTextFieldChanged(GTextField source, GEvent event) { //_CODE_:gridSizeTextField:502004:
  n = parseInt( gridSizeTextField.getText() );
  resetGrid();
  pauseButton.setText("Go");
} //_CODE_:gridSizeTextField:502004:


public void clearButtonClicked(GButton source, GEvent event) { //_CODE_:clearButton:541797:
  resetGrid();
  pauseButton.setText("Go");
} //_CODE_:clearButton:541797:



// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.BLUE_SCHEME);
  G4P.setCursor(ARROW);
  surface.setTitle("Sketch Window");
  controlsWindow = GWindow.getWindow(this, "Controls", 0, 0, 200, 300, JAVA2D);
  controlsWindow.noLoop();
  controlsWindow.addDrawHandler(this, "win_draw1");
  pauseButton = new GButton(controlsWindow, 20, 70, 80, 30);
  pauseButton.setText("Go");
  pauseButton.addEventHandler(this, "pauseButtonClicked");
  label1 = new GLabel(controlsWindow, 20, 20, 80, 20);
  label1.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  label1.setText("Grid size");
  label1.setOpaque(false);
  gridSizeTextField = new GTextField(controlsWindow, 110, 20, 50, 30, G4P.SCROLLBARS_NONE);
  gridSizeTextField.setText("10");
  gridSizeTextField.setOpaque(true);
  gridSizeTextField.addEventHandler(this, "gridSizeTextFieldChanged");
  clearButton = new GButton(controlsWindow, 20, 120, 80, 30);
  clearButton.setText("Clear");
  clearButton.addEventHandler(this, "clearButtonClicked");
  controlsWindow.loop();
}

// Variable declarations 
// autogenerated do not edit
GWindow controlsWindow;
GButton pauseButton; 
GLabel label1; 
GTextField gridSizeTextField; 
GButton clearButton; 
