/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */

synchronized public void win_draw1(PApplet appc, GWinData data) { //_CODE_:window1:748785:
  appc.background(230);
} //_CODE_:window1:748785:

public void aSliderChanged(GCustomSlider source, GEvent event) { //_CODE_:aSlider:205693:
  resetValues();
} //_CODE_:aSlider:205693:

public void focusSliderChanged(GCustomSlider source, GEvent event) { //_CODE_:focusSlider:714385:
  resetValues();  //1-10
} //_CODE_:focusSlider:714385:

public void focusButtonClicked(GButton source, GEvent event) { //_CODE_:focusButton:707104:
  yBulb = 1/(4*a);
  int newSliderValue = int(yBulb * 100);
  focusSlider.setValue( newSliderValue );
  redraw();
} //_CODE_:focusButton:707104:



// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.BLUE_SCHEME);
  G4P.setCursor(ARROW);
  surface.setTitle("Sketch Window");
  window1 = GWindow.getWindow(this, "Window title", 0, 0, 700, 200, JAVA2D);
  window1.noLoop();
  window1.addDrawHandler(this, "win_draw1");
  aSlider = new GCustomSlider(window1, 84, 32, 560, 40, "grey_blue");
  aSlider.setShowValue(true);
  aSlider.setShowLimits(true);
  aSlider.setLimits(500, 0, 1000);
  aSlider.setNbrTicks(10);
  aSlider.setNumberFormat(G4P.INTEGER, 0);
  aSlider.setOpaque(false);
  aSlider.addEventHandler(this, "aSliderChanged");
  label1 = new GLabel(window1, 4, 40, 70, 20);
  label1.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  label1.setText("Curvature");
  label1.setOpaque(false);
  label2 = new GLabel(window1, 0, 90, 80, 20);
  label2.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  label2.setText("Bulb distance");
  label2.setOpaque(false);
  focusSlider = new GCustomSlider(window1, 84, 90, 560, 41, "grey_blue");
  focusSlider.setLimits(500, 0, 1000);
  focusSlider.setNbrTicks(10);
  focusSlider.setNumberFormat(G4P.INTEGER, 0);
  focusSlider.setOpaque(false);
  focusSlider.addEventHandler(this, "focusSliderChanged");
  focusButton = new GButton(window1, 7, 150, 80, 30);
  focusButton.setText("Autofocus");
  focusButton.setLocalColorScheme(GCScheme.GREEN_SCHEME);
  focusButton.addEventHandler(this, "focusButtonClicked");
  window1.loop();
}

// Variable declarations 
// autogenerated do not edit
GWindow window1;
GCustomSlider aSlider; 
GLabel label1; 
GLabel label2; 
GCustomSlider focusSlider; 
GButton focusButton; 
