/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */

synchronized public void win_draw1(PApplet appc, GWinData data) { //_CODE_:window1:392428:
  appc.background(230);
} //_CODE_:window1:392428:

public void button1_click1(GButton source, GEvent event) { //_CODE_:button1:865264:
  println("button1 - GButton >> GEvent." + event + " @ " + millis());
  reset();
} //_CODE_:button1:865264:

public void custom_slider1_change1(GCustomSlider source, GEvent event) { //_CODE_:hip:725729:
  println("hip - GCustomSlider >> GEvent." + event + " @ " + millis());
} //_CODE_:hip:725729:

public void custom_slider1_change2(GCustomSlider source, GEvent event) { //_CODE_:knee:621004:
  println("knee - GCustomSlider >> GEvent." + event + " @ " + millis());
} //_CODE_:knee:621004:

public void custom_slider1_change3(GCustomSlider source, GEvent event) { //_CODE_:heel:646038:
  println("heel - GCustomSlider >> GEvent." + event + " @ " + millis());
} //_CODE_:heel:646038:

public void button2_click1(GButton source, GEvent event) { //_CODE_:button2:604831:
  println("button2 - GButton >> GEvent." + event + " @ " + millis());
} //_CODE_:button2:604831:

public void button3_click1(GButton source, GEvent event) { //_CODE_:button3:747912:
  println("button3 - GButton >> GEvent." + event + " @ " + millis());
} //_CODE_:button3:747912:

public void button4_click1(GButton source, GEvent event) { //_CODE_:button4:757285:
  println("button4 - GButton >> GEvent." + event + " @ " + millis());
} //_CODE_:button4:757285:

public void button5_click1(GButton source, GEvent event) { //_CODE_:button5:544722:
  println("button5 - GButton >> GEvent." + event + " @ " + millis());
} //_CODE_:button5:544722:

public void button6_click1(GButton source, GEvent event) { //_CODE_:button6:994383:
  println("button6 - GButton >> GEvent." + event + " @ " + millis());
} //_CODE_:button6:994383:



// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.BLUE_SCHEME);
  G4P.setMouseOverEnabled(false);
  surface.setTitle("Sketch Window");
  window1 = GWindow.getWindow(this, "Window title", 0, 0, 240, 300, JAVA2D);
  window1.noLoop();
  window1.setActionOnClose(G4P.KEEP_OPEN);
  window1.addDrawHandler(this, "win_draw1");
  button1 = new GButton(window1, 15, 17, 80, 30);
  button1.setText("Reset");
  button1.addEventHandler(this, "button1_click1");
  hip = new GCustomSlider(window1, 120, 28, 100, 40, "grey_blue");
  hip.setLimits(0.5, 0.0, 1.0);
  hip.setNumberFormat(G4P.DECIMAL, 2);
  hip.setOpaque(false);
  hip.addEventHandler(this, "custom_slider1_change1");
  knee = new GCustomSlider(window1, 118, 94, 100, 40, "grey_blue");
  knee.setLimits(0.5, 0.0, 1.0);
  knee.setNumberFormat(G4P.DECIMAL, 2);
  knee.setOpaque(false);
  knee.addEventHandler(this, "custom_slider1_change2");
  heel = new GCustomSlider(window1, 130, 158, 100, 40, "grey_blue");
  heel.setLimits(0.5, 0.0, 1.0);
  heel.setNumberFormat(G4P.DECIMAL, 2);
  heel.setOpaque(false);
  heel.addEventHandler(this, "custom_slider1_change3");
  button2 = new GButton(window1, 16, 71, 80, 30);
  button2.setText("Record Thigh");
  button2.addEventHandler(this, "button2_click1");
  button3 = new GButton(window1, 14, 126, 80, 30);
  button3.setText("Record Calf");
  button3.addEventHandler(this, "button3_click1");
  button4 = new GButton(window1, 17, 183, 80, 30);
  button4.setText("Record Foot");
  button4.addEventHandler(this, "button4_click1");
  button5 = new GButton(window1, 129, 250, 80, 30);
  button5.setText("Demo");
  button5.addEventHandler(this, "button5_click1");
  button6 = new GButton(window1, 17, 246, 80, 30);
  button6.setText("Play Record");
  button6.addEventHandler(this, "button6_click1");
  window1.loop();
}

// Variable declarations 
// autogenerated do not edit
GWindow window1;
GButton button1; 
GCustomSlider hip; 
GCustomSlider knee; 
GCustomSlider heel; 
GButton button2; 
GButton button3; 
GButton button4; 
GButton button5; 
GButton button6; 
