/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */

synchronized public void parameters_draw(PApplet appc, GWinData data) { //_CODE_:parameters:901620:
  appc.background(230);
} //_CODE_:parameters:901620:

public void distanceSliderChanged(GCustomSlider source, GEvent event) { //_CODE_:distanceSlider:410767:
  img.dist = distanceSlider.getValueF();
  lensedImg.dist = distanceSlider.getValueF();
} //_CODE_:distanceSlider:410767:

public void powerSliderChanged(GCustomSlider source, GEvent event) { //_CODE_:powerSlider:356160:
  e.changePower(powerSlider.getValueF());
  e.changeLensedPower();
  img.changeNPFP(e.nearPoint, e.farPoint);
  lensedImg.changeNPFP(e.lensedNP, e.lensedFP);
} //_CODE_:powerSlider:356160:

public void imgTextboxChanged(GTextField source, GEvent event) { //_CODE_:imgTextbox:972962:
  img.changeImage(imgTextbox.getText());
  lensedImg.changeImage(imgTextbox.getText());
} //_CODE_:imgTextbox:972962:

public void lensSliderChanged(GCustomSlider source, GEvent event) { //_CODE_:lensSlider:207585:
  l.changePower(lensSlider.getValueF());
  lensedImg.changeNPFP(e.lensedNP, e.lensedFP);
} //_CODE_:lensSlider:207585:



// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.BLUE_SCHEME);
  G4P.setMouseOverEnabled(false);
  surface.setTitle("Sketch Window");
  parameters = GWindow.getWindow(this, "Parameters", 0, 0, 140, 420, JAVA2D);
  parameters.noLoop();
  parameters.setActionOnClose(G4P.CLOSE_WINDOW);
  parameters.addDrawHandler(this, "parameters_draw");
  distanceSlider = new GCustomSlider(parameters, 20, 60, 100, 40, "grey_blue");
  distanceSlider.setLimits(0.25, 0.01, 5.0);
  distanceSlider.setNumberFormat(G4P.DECIMAL, 2);
  distanceSlider.setOpaque(false);
  distanceSlider.addEventHandler(this, "distanceSliderChanged");
  powerSlider = new GCustomSlider(parameters, 20, 140, 100, 40, "grey_blue");
  powerSlider.setLimits(0.0, -1.99, 1.99);
  powerSlider.setNumberFormat(G4P.DECIMAL, 2);
  powerSlider.setOpaque(false);
  powerSlider.addEventHandler(this, "powerSliderChanged");
  imgTextbox = new GTextField(parameters, 20, 300, 100, 40, G4P.SCROLLBARS_NONE);
  imgTextbox.setPromptText("Include Extension (.jpg, .png, .gif)");
  imgTextbox.setOpaque(true);
  imgTextbox.addEventHandler(this, "imgTextboxChanged");
  label1 = new GLabel(parameters, 0, 40, 140, 20);
  label1.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  label1.setText("Object Distance (m)");
  label1.setOpaque(false);
  label2 = new GLabel(parameters, 0, 80, 40, 20);
  label2.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  label2.setText("0.01");
  label2.setOpaque(false);
  label3 = new GLabel(parameters, 100, 80, 40, 20);
  label3.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  label3.setText("5");
  label3.setOpaque(false);
  label4 = new GLabel(parameters, 0, 120, 140, 20);
  label4.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  label4.setText("Eye Lens Power (dtp)");
  label4.setOpaque(false);
  label6 = new GLabel(parameters, 0, 160, 40, 20);
  label6.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  label6.setText("-2");
  label6.setOpaque(false);
  label7 = new GLabel(parameters, 100, 160, 40, 20);
  label7.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  label7.setText("+2");
  label7.setOpaque(false);
  label5 = new GLabel(parameters, 0, 280, 140, 20);
  label5.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  label5.setText("Image File Name");
  label5.setOpaque(false);
  lensSlider = new GCustomSlider(parameters, 20, 220, 100, 40, "grey_blue");
  lensSlider.setLimits(0.0, -1.99, 1.99);
  lensSlider.setNumberFormat(G4P.DECIMAL, 2);
  lensSlider.setOpaque(false);
  lensSlider.addEventHandler(this, "lensSliderChanged");
  label8 = new GLabel(parameters, 0, 200, 140, 20);
  label8.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  label8.setText("Specs Lens Power (dtp)");
  label8.setOpaque(false);
  label9 = new GLabel(parameters, 0, 240, 40, 20);
  label9.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  label9.setText("-2");
  label9.setOpaque(false);
  label10 = new GLabel(parameters, 100, 240, 40, 20);
  label10.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  label10.setText("+2");
  label10.setOpaque(false);
  label11 = new GLabel(parameters, 0, 340, 140, 20);
  label11.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  label11.setText("To Access Images:");
  label11.setTextItalic();
  label11.setOpaque(false);
  label12 = new GLabel(parameters, 0, 360, 140, 20);
  label12.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  label12.setText("Add 256x256 images to");
  label12.setTextItalic();
  label12.setOpaque(false);
  label13 = new GLabel(parameters, 0, 380, 140, 20);
  label13.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  label13.setText("the 'data' folder");
  label13.setTextItalic();
  label13.setOpaque(false);
  label14 = new GLabel(parameters, 0, 20, 140, 20);
  label14.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  label14.setText("Parameters");
  label14.setTextBold();
  label14.setOpaque(false);
  label15 = new GLabel(parameters, 0, 180, 40, 20);
  label15.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  label15.setText("(far)");
  label15.setOpaque(false);
  label16 = new GLabel(parameters, 100, 180, 40, 20);
  label16.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  label16.setText("(near)");
  label16.setOpaque(false);
  parameters.loop();
}

// Variable declarations 
// autogenerated do not edit
GWindow parameters;
GCustomSlider distanceSlider; 
GCustomSlider powerSlider; 
GTextField imgTextbox; 
GLabel label1; 
GLabel label2; 
GLabel label3; 
GLabel label4; 
GLabel label6; 
GLabel label7; 
GLabel label5; 
GCustomSlider lensSlider; 
GLabel label8; 
GLabel label9; 
GLabel label10; 
GLabel label11; 
GLabel label12; 
GLabel label13; 
GLabel label14; 
GLabel label15; 
GLabel label16; 
