/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */

synchronized public void win_draw1(PApplet appc, GWinData data) { //_CODE_:puzzleBuilder:809305:
  appc.background(230);
} //_CODE_:puzzleBuilder:809305:

public void buildPreset1(GButton source, GEvent event) { //_CODE_:preset1:823925:
  String[] list = loadStrings("Puzzle1.txt");

  loadPuzzle(list);
} //_CODE_:preset1:823925:

public void buildPreset2(GButton source, GEvent event) { //_CODE_:preset2:278820:
  String[] list = loadStrings("Puzzle2.txt");

  loadPuzzle(list);
} //_CODE_:preset2:278820:

public void buildPreset3(GButton source, GEvent event) { //_CODE_:preset3:445413:
  String[] list = loadStrings("Puzzle3.txt");

  loadPuzzle(list);
} //_CODE_:preset3:445413:

public void solvePuzzle(GButton source, GEvent event) { //_CODE_:solveButton:694338:
  if (puzzleSolve.get(0).gridX != 4)
    solvePuzzle();
} //_CODE_:solveButton:694338:

public void reset(GButton source, GEvent event) { //_CODE_:resetButton:314028:
  String[] list = loadStrings("Puzzle0.txt");

  loadPuzzle(list);
} //_CODE_:resetButton:314028:

public void selectBlock1(GButton source, GEvent event) { //_CODE_:block1:251668:
  newBlock = 1;
} //_CODE_:block1:251668:

public void selectBlock3(GButton source, GEvent event) { //_CODE_:block3:511210:
  newBlock = 3;
} //_CODE_:block3:511210:

public void selectBlock2(GButton source, GEvent event) { //_CODE_:block2:941832:
  newBlock = 2;
} //_CODE_:block2:941832:

public void selectBlock4(GButton source, GEvent event) { //_CODE_:block4:447518:
  newBlock = 4;
} //_CODE_:block4:447518:

public void undo(GButton source, GEvent event) { //_CODE_:undoButton:315062:
  removeLastBlock();
} //_CODE_:undoButton:315062:

synchronized public void win_draw2(PApplet appc, GWinData data) { //_CODE_:textWindow:597639:
  appc.background(230);
} //_CODE_:textWindow:597639:

public void textarea1_change1(GTextArea source, GEvent event) { //_CODE_:rulesText:325322:
} //_CODE_:rulesText:325322:

public void noteChange(GTextField source, GEvent event) { //_CODE_:note:981785:
} //_CODE_:note:981785:



// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.BLUE_SCHEME);
  G4P.setCursor(ARROW);
  surface.setTitle("Puzzle Window");
  puzzleBuilder = GWindow.getWindow(this, "Selection Window", 0, 0, 400, 210, JAVA2D);
  puzzleBuilder.noLoop();
  puzzleBuilder.addDrawHandler(this, "win_draw1");
  preset1 = new GButton(puzzleBuilder, 270, 20, 108, 30);
  preset1.setText("Preset 1");
  preset1.addEventHandler(this, "buildPreset1");
  preset2 = new GButton(puzzleBuilder, 270, 60, 110, 30);
  preset2.setText("Preset 2");
  preset2.addEventHandler(this, "buildPreset2");
  preset3 = new GButton(puzzleBuilder, 270, 100, 110, 30);
  preset3.setText("Preset 3");
  preset3.addEventHandler(this, "buildPreset3");
  solveButton = new GButton(puzzleBuilder, 210, 160, 170, 30);
  solveButton.setText("Solve");
  solveButton.addEventHandler(this, "solvePuzzle");
  resetButton = new GButton(puzzleBuilder, 20, 160, 170, 30);
  resetButton.setText("Reset Board");
  resetButton.addEventHandler(this, "reset");
  block1 = new GButton(puzzleBuilder, 100, 10, 80, 40);
  block1.setLocalColorScheme(GCScheme.GREEN_SCHEME);
  block1.addEventHandler(this, "selectBlock1");
  block3 = new GButton(puzzleBuilder, 190, 10, 40, 80);
  block3.setLocalColorScheme(GCScheme.GOLD_SCHEME);
  block3.addEventHandler(this, "selectBlock3");
  block2 = new GButton(puzzleBuilder, 100, 100, 130, 40);
  block2.setLocalColorScheme(GCScheme.RED_SCHEME);
  block2.addEventHandler(this, "selectBlock2");
  block4 = new GButton(puzzleBuilder, 50, 10, 40, 130);
  block4.setLocalColorScheme(GCScheme.CYAN_SCHEME);
  block4.addEventHandler(this, "selectBlock4");
  undoButton = new GButton(puzzleBuilder, 100, 60, 80, 30);
  undoButton.setText("Remove Last");
  undoButton.addEventHandler(this, "undo");
  textWindow = GWindow.getWindow(this, "Rules Window", 0, 0, 400, 200, JAVA2D);
  textWindow.noLoop();
  textWindow.addDrawHandler(this, "win_draw2");
  rulesText = new GTextArea(textWindow, 20, 10, 360, 140, G4P.SCROLLBARS_NONE);
  rulesText.setText("test");
  rulesText.setLocalColorScheme(GCScheme.GREEN_SCHEME);
  rulesText.setOpaque(true);
  rulesText.addEventHandler(this, "textarea1_change1");
  note = new GTextField(textWindow, 20, 160, 280, 30, G4P.SCROLLBARS_NONE);
  note.setLocalColorScheme(GCScheme.YELLOW_SCHEME);
  note.setOpaque(true);
  note.addEventHandler(this, "noteChange");
  puzzleBuilder.loop();
  textWindow.loop();
}

// Variable declarations 
// autogenerated do not edit
GWindow puzzleBuilder;
GButton preset1; 
GButton preset2; 
GButton preset3; 
GButton solveButton; 
GButton resetButton; 
GButton block1; 
GButton block3; 
GButton block2; 
GButton block4; 
GButton undoButton; 
GWindow textWindow;
GTextArea rulesText; 
GTextField note; 
