/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */

synchronized public void win_draw1(PApplet appc, GWinData data) { //_CODE_:window1:320575:
  appc.background(230);
} //_CODE_:window1:320575:

public void button1_click1(GButton source, GEvent event) { //_CODE_:song1:466706:
  songChoice = 1;
 println(songChoice);
} //_CODE_:song1:466706:

public void button2_click1(GButton source, GEvent event) { //_CODE_:song2:403389:
   songChoice = 2;
  println(songChoice);
} //_CODE_:song2:403389:

public void button3_click1(GButton source, GEvent event) { //_CODE_:song3:791852:
  songChoice = 3;
 println(songChoice);
} //_CODE_:song3:791852:

public void button4_click1(GButton source, GEvent event) { //_CODE_:song4:656087:
  songChoice = 4;
 println(songChoice);
} //_CODE_:song4:656087:

public void button5_click1(GButton source, GEvent event) { //_CODE_:song5:449053:
   songChoice = 5;
  println(songChoice);
} //_CODE_:song5:449053:

public void button1_click2(GButton source, GEvent event) { //_CODE_:button1:729494:
 filterType = THRESHOLD;
} //_CODE_:button1:729494:

public void button2_click2(GButton source, GEvent event) { //_CODE_:button2:669742:
  filterType = INVERT;
} //_CODE_:button2:669742:

public void button3_click2(GButton source, GEvent event) { //_CODE_:button3:271776:
  filterType = GRAY;
} //_CODE_:button3:271776:

public void button4_click2(GButton source, GEvent event) { //_CODE_:button4:437061:
  filterType = 0;
} //_CODE_:button4:437061:



// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.BLUE_SCHEME);
  G4P.setMouseOverEnabled(false);
  surface.setTitle("Sketch Window");
  window1 = GWindow.getWindow(this, "Personalize", 0, 0, 400, 400, JAVA2D);
  window1.noLoop();
  window1.setActionOnClose(G4P.KEEP_OPEN);
  window1.addDrawHandler(this, "win_draw1");
  song1 = new GButton(window1, 9, 13, 192, 30);
  song1.setText("Playboi Carti - Go2DaMoon");
  song1.setLocalColorScheme(GCScheme.GREEN_SCHEME);
  song1.addEventHandler(this, "button1_click1");
  song2 = new GButton(window1, 9, 48, 192, 30);
  song2.setText("Yung Lean - Agony");
  song2.setLocalColorScheme(GCScheme.GREEN_SCHEME);
  song2.addEventHandler(this, "button2_click1");
  song3 = new GButton(window1, 9, 85, 192, 30);
  song3.setText("Cigarettes After Sex - Apocalypse");
  song3.setLocalColorScheme(GCScheme.GREEN_SCHEME);
  song3.addEventHandler(this, "button3_click1");
  song4 = new GButton(window1, 9, 123, 192, 30);
  song4.setText("Lil Soda Boi - Plug Me In");
  song4.setLocalColorScheme(GCScheme.GREEN_SCHEME);
  song4.addEventHandler(this, "button4_click1");
  song5 = new GButton(window1, 9, 161, 192, 30);
  song5.setText("BROCKHAMPTON - BOOGIE");
  song5.setLocalColorScheme(GCScheme.GREEN_SCHEME);
  song5.addEventHandler(this, "button5_click1");
  label1 = new GLabel(window1, 221, 16, 157, 151);
  label1.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  label1.setText("There is an issue with the GUI where when you click the song you'd like to play, it'll be stuck on the first millisecond of the song. To bypass this, after clicking on your preferred song, click on Playboi Carti - Go2DaMoon. This applies for every song on the GUI");
  label1.setLocalColorScheme(GCScheme.GREEN_SCHEME);
  label1.setOpaque(true);
  button1 = new GButton(window1, 11, 359, 80, 30);
  button1.setText("Threshold");
  button1.setLocalColorScheme(GCScheme.GREEN_SCHEME);
  button1.addEventHandler(this, "button1_click2");
  button2 = new GButton(window1, 107, 359, 80, 30);
  button2.setText("Invert");
  button2.setLocalColorScheme(GCScheme.GREEN_SCHEME);
  button2.addEventHandler(this, "button2_click2");
  button3 = new GButton(window1, 207, 359, 80, 30);
  button3.setText("Gray");
  button3.setLocalColorScheme(GCScheme.GREEN_SCHEME);
  button3.addEventHandler(this, "button3_click2");
  button4 = new GButton(window1, 302, 359, 80, 30);
  button4.setText("Reset");
  button4.setLocalColorScheme(GCScheme.GREEN_SCHEME);
  button4.addEventHandler(this, "button4_click2");
  label3 = new GLabel(window1, 149, 334, 80, 20);
  label3.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  label3.setText("Filter Gallery");
  label3.setOpaque(false);
  window1.loop();
}

// Variable declarations 
// autogenerated do not edit
GWindow window1;
GButton song1; 
GButton song2; 
GButton song3; 
GButton song4; 
GButton song5; 
GLabel label1; 
GButton button1; 
GButton button2; 
GButton button3; 
GButton button4; 
GLabel label3; 
